export const HEROES_REQUEST = 'HEROES_REQUEST'
export const HEROES_RESPONSE = 'HEROES_RESPONSE'
export const HEROES_ERROR = 'HEROES_ERROR'

export const HERO_PROFILE_REQUEST = 'HERO_PROFILE_REQUEST'
export const HERO_PROFILE_RESPONSE = 'HERO_PROFILE_RESPONSE'
export const HERO_PROFILE_ERROR = 'HERO_PROFILE_ERROR'

export const HERO_PROFILE_SUBMIT_REQUEST = 'HERO_PROFILE_SUBMIT_REQUEST'
export const HERO_PROFILE_SUBMIT_RESPONSE = 'HERO_PROFILE_SUBMIT_RESPONSE'
export const HERO_PROFILE_SUBMIT_ERROR = 'HERO_PROFILE_SUBMIT_ERROR'

export const HERO_ATTR_UPDATE = 'HERO_ATTR_UPDATE'
export const HERO_ATTR_SET = 'HERO_ATTR_SET'
export const HERO_REMAIN_SET = 'HERO_REMAIN_SET'


// Action key that carries API call info interpreted by this Redux middleware
export const CALL_API = 'CALL_API'
